'use strict';
const $=id=>document.getElementById(id), names={qwen:'Qwen',deepseek:'DeepSeek',alice:'Алиса / YandexGPT',kimi:'Kimi'};
let candidates=[],current=null,reply=null,pollTimer=null,busy=false,artifactKey=null,savedPayload=null,generation=0,selectionBusy=false;
const calls=new Map(), linksKey='neuromorph-assistant-links-v1';
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function provider(raw){try{const u=new URL(raw);if(u.protocol!=='https:'||u.username||u.password||u.hash||(u.port&&u.port!=='443')||[...u.searchParams.keys()].some(k=>/^(access_token|refresh_token|api_key|authorization|password|token)$/i.test(k)))return null;if(u.hostname==='chat.qwen.ai')return'qwen';if(u.hostname==='chat.deepseek.com')return'deepseek';if(u.hostname==='alice.yandex.ru'||u.hostname==='yandex.ru'&&/^\/alice(?:\/|$)/.test(u.pathname))return'alice';if(['kimi.com','www.kimi.com','kimi.ai','www.kimi.ai'].includes(u.hostname))return'kimi';}catch{}return null;}
function request(action,payload={}){const id=crypto.randomUUID();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{calls.delete(id);reject(new Error('Нет ответа расширения. После отправки не повторяйте запрос: проверьте чат и ожидающую задачу.'));},12000);calls.set(id,{resolve,reject,timer});window.postMessage({channel:'neuromorph-request-v1',id,action,payload},location.origin);});}
window.addEventListener('message',event=>{if(event.source!==window||event.origin!==location.origin||event.data?.channel!=='neuromorph-response-v1')return;const call=calls.get(event.data.id);if(!call)return;clearTimeout(call.timer);calls.delete(event.data.id);call.resolve(event.data.result);});
const labels={composer_visible:'Поле ввода видно · вход не подтверждён',sign_in_control_visible:'Видна кнопка входа',challenge_visible:'Проверка пользователя · отправка заблокирована',limit_visible:'Видно ограничение сервиса',unknown:'Состояние неизвестно',unavailable:'Не удалось прочитать страницу'};
function renderCandidates(list){candidates=Array.isArray(list)?list:[];const old=$('target').value;$('target').replaceChildren(new Option('Выберите конкретный чат',''));$('candidates').replaceChildren();for(const c of candidates){if(provider(c.url)!==c.provider)continue;const card=document.createElement('article');card.className='candidate';const h=document.createElement('h3');h.textContent=names[c.provider];const p=document.createElement('p');p.textContent=labels[c.observation]||'Состояние неизвестно';const a=document.createElement('a');a.href=c.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Открыть выбранный чат ↗';card.append(h,p,a);$('candidates').append(card);$('target').append(new Option(names[c.provider]+' · вкладка '+c.tab_id,String(c.tab_id)));}if(!candidates.length){const p=document.createElement('p');p.textContent='Разрешённых вкладок не обнаружено. Установите расширение, выдайте доступ выбранному сайту и включите проверку.';$('candidates').append(p);}if([...$('target').options].some(x=>x.value===old))$('target').value=old;}
function advance(){generation++;clearTimeout(pollTimer);pollTimer=null;}
function snapshot(){if(!current)throw new Error('Сначала отправьте задание или выберите вкладку для ручного переноса.');return Object.freeze({...current,generation});}
function active(s){return s.generation===generation&&current?.task_id===s.task_id&&current?.provider===s.provider&&current?.chat_url===s.chat_url&&current?.tab_id===s.tab_id;}
function bound(r,s){return r?.task_id===s.task_id&&r?.provider===s.provider&&r?.chat_url===s.chat_url;}
function payload(s=snapshot()){return {task_id:s.task_id,tab_id:s.tab_id,provider:s.provider,url:s.chat_url};}
function clearArtifact(){reply=null;artifactKey=null;savedPayload=null;$('verified').checked=false;}
function acceptReply(r){clearArtifact();reply=r;$('answer').value=r.text;}
async function refresh(){const before=generation;try{const s=await request('status');if(!s?.ok)throw new Error(s?.error||'Мост не отвечает.');const r=await request('scan');renderCandidates(r.candidates);if(before!==generation||busy)return;if(s.pending){if(!current||current.task_id!==s.pending.task_id){advance();clearArtifact();$('answer').value='';current=s.pending;}$('task-status').textContent='Ожидает проверки: '+current.task_id+' · '+(current.status||'не подтверждено');$('send').disabled=true;}else{$('send').disabled=false;}notice(s.scan?'Мост доступен. Сканирование разрешённых вкладок включено.':'Мост доступен. Включите проверку вкладок в его панели.');}catch(e){if(before===generation)notice(e.message,true);}}
async function poll(s){if(!active(s)||s.provider!=='deepseek')return;try{const r=await request('capture',payload(s));if(!active(s))return;if(!r.ok)throw new Error(r.error);if(!bound(r,s))throw new Error('Ответ не относится к ожидающей задаче. Импорт отменён.');if(r.status==='captured_unconfirmed'){acceptReply(r);$('task-status').textContent='Новый текст возвращён автоматически. Сверьте полноту и принадлежность ответа перед сохранением.';return;}if(r.status==='waiting_unconfirmed'){pollTimer=setTimeout(()=>poll(s),3000);return;}$('task-status').textContent='Автоприём остановлен: '+r.status+'. Можно выделить ответ или перенести вручную.';}catch(e){if(active(s))$('task-status').textContent=e.message;}}
$('refresh').onclick=refresh;
$('send').onclick=async()=>{if(busy)return;const c=candidates.find(x=>String(x.tab_id)===$('target').value),text=$('prompt').value.trim();if(!c||!text||!$('consent').checked)return notice('Выберите вкладку, введите вопрос и подтвердите передачу.',true);advance();busy=true;$('send').disabled=true;clearArtifact();$('answer').value='';current={task_id:crypto.randomUUID(),tab_id:c.tab_id,provider:c.provider,chat_url:c.url,created_at:new Date().toISOString()};const s=snapshot();try{const r=await request('dispatch',{...payload(s),prompt:'[NeuroMorf task_id: '+s.task_id+']\n'+text});if(!active(s))return;if(r.ok&&!bound(r,s))throw new Error('Квитанция отправки не совпадает с задачей. Проверьте чат вручную.');current={...current,...r};$('task-status').textContent=(r.notice||r.error||r.status)+'\nTask: '+s.task_id;notice(r.ok?'Одна попытка выполнена. Проверьте её в выбранном чате.':r.error,!r.ok);if(r.status==='send_clicked_unconfirmed'&&c.provider==='deepseek')pollTimer=setTimeout(()=>poll(s),3000);}catch(e){if(active(s))notice(e.message,true);}finally{busy=false;}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('prompt').value);notice('Вопрос скопирован. Отправьте его в выбранном чате самостоятельно.');}catch{notice('Буфер обмена недоступен: выделите текст вопроса и скопируйте вручную.',true);}};
$('get-selection').onclick=async()=>{if(busy||selectionBusy)return;let s;try{if(!current){const c=candidates.find(x=>String(x.tab_id)===$('target').value);if(!c)throw new Error('Выберите вкладку.');current={task_id:crypto.randomUUID(),tab_id:c.tab_id,provider:c.provider,chat_url:c.url,created_at:new Date().toISOString(),status:'manual_transfer'};}advance();clearArtifact();s=snapshot();selectionBusy=true;const r=await request('selection',payload(s));if(!active(s))return;if(!r.ok)throw new Error(r.error);if(!bound(r,s))throw new Error('Выделение не относится к выбранной задаче. Импорт отменён.');acceptReply(r);notice('Выделенный текст возвращён. Сверьте его принадлежность и полноту.');}catch(e){if(!s||active(s))notice(e.message,true);}finally{selectionBusy=false;}};
$('answer').oninput=()=>{advance();clearArtifact();};
$('project').onchange=()=>{artifactKey=null;savedPayload=null;};
function artifact(){const text=$('answer').value.trim();if(!text||!$('verified').checked)throw new Error('Добавьте ответ и подтвердите сверку с чатом.');return {schema_version:1,task_id:current?.task_id||crypto.randomUUID(),provider:current?.provider||'manual',chat_url:current?.chat_url||'',created_at:current?.created_at||null,imported_at:new Date().toISOString(),capture:reply?.verification||'manual_import',completion:'human_checked',scientific_validation:false,text};}
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',...options});const data=await r.json();if(!r.ok)throw new Error(data.error?.message||'Сервер недоступен ('+r.status+')');return data;}
$('save').onclick=async()=>{try{const a=artifact(),project=$('project').value,started=generation;if(!project)throw new Error('Создайте и выберите проект в исследовательском пространстве.');const session=await api('/api/session');if(started!==generation||project!==$('project').value||a.text!==$('answer').value.trim()||!$('verified').checked)throw new Error('Материал изменился во время проверки сессии. Сохранение отменено; проверьте текущий текст.');const headers={'Content-Type':'application/json'};if(session.csrf_token)headers['X-CSRF-Token']=session.csrf_token;if(!artifactKey){artifactKey=crypto.randomUUID();savedPayload=null;}const body=JSON.stringify({...a,text:undefined},null,2)+'\n\n'+a.text;if(body.length>12000)throw new Error('Для материала слишком длинный текст. Сократите ответ или экспортируйте JSON.');savedPayload ||= {kind:'artifact',idempotency_key:artifactKey,project_id:project,title:'Ответ '+(names[a.provider]||'ассистента')+' · '+a.task_id.slice(0,8),body,source_url:a.chat_url,evidence:'unreviewed'};await api('/api/studio/save',{method:'POST',headers,body:JSON.stringify(savedPayload)});if(started===generation)notice('Материал сохранён в проекте как непроверенный. Научная рецензия — следующий шаг.');}catch(e){notice(e.message,true);}};
$('export').onclick=()=>{try{const a=artifact(),url=URL.createObjectURL(new Blob([JSON.stringify(a,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='neuromorph-'+a.task_id+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notice(e.message,true);}};
$('resolve').onclick=async()=>{if(!current||busy)return;if(!confirm('Вы лично проверили чат: отправка могла уже состояться. Закрыть ожидание без повторной отправки?'))return;advance();const s=snapshot();busy=true;try{const r=await request('resolve',{task_id:s.task_id,confirmed:true});if(!active(s))return;if(!r.ok)throw new Error(r.error);current={...current,status:'resolved'};$('send').disabled=false;notice('Ожидание закрыто. Повторная отправка не выполнялась.');}catch(e){if(active(s))notice(e.message,true);}finally{busy=false;}};
function links(){try{return JSON.parse(localStorage.getItem(linksKey)||'[]').filter(x=>typeof x==='string'&&provider(x)).slice(0,20);}catch{return[];}}
function renderLinks(){$('saved-links').replaceChildren();for(const url of links()){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=names[provider(url)]+' · '+url;$('saved-links').append(a);}}
$('url-form').onsubmit=e=>{e.preventDefault();const url=$('provider-url').value.trim();if(!provider(url))return notice('Разрешены только HTTPS-адреса Qwen, DeepSeek, Алисы и Kimi без credentials.',true);try{localStorage.setItem(linksKey,JSON.stringify([...new Set([...links(),url])].slice(-20)));renderLinks();notice('Ссылка сохранена локально. Откройте чат и разрешите сайт в расширении.');}catch{notice('Локальное хранилище недоступно.',true);}};
$('clear-links').onclick=()=>{localStorage.removeItem(linksKey);renderLinks();};
async function projects(){try{const s=await api('/api/studio');$('project').replaceChildren(new Option('Выберите проект',''));for(const p of s.projects||[])$('project').append(new Option(p.title,p.id));}catch{$('project').replaceChildren(new Option('Проекты недоступны — используйте экспорт',''));}}
renderLinks();projects();refresh();
// Read only extension observations. Discovery never dispatches a model task.
setInterval(async()=>{if(document.hidden)return;try{const s=await request('status');if(!s?.ok||!s.scan)return;const before=new Set(candidates.map(c=>c.tab_id+':'+c.url));const list=s.candidates||[];renderCandidates(list);if(list.some(c=>!before.has(c.tab_id+':'+c.url)))notice('Обнаружена новая разрешённая вкладка. Вы можете выбрать её для исследования; вход в аккаунт ещё не подтверждён.');}catch{}},60000);
