"use strict";
(() => {
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => Array.from(root.querySelectorAll(selector));
  const state = { network: null, campaigns: [], accounts: [], resources: [], section: "network", refreshing: false, resourcesVersion: null, searchSerial: 0, toastTimer: null };
  const titles = { network: "Состояние сети", resources: "Ресурсы и поиск", campaigns: "Исследования", accounts: "Подключения" };
  const terminal = new Set(["completed", "failed", "cancelled", "budget_exhausted"]);
  const labels = {
    metadata_provider: "Поиск метаданных", scientific_platform: "Научная платформа", builtin_control: "Контрольная модель", dataset_platform: "Платформа данных", builtin: "Встроенный модуль", documentation_public: "Открытая документация", local_stdlib: "Локальный модуль", code_public_weights_separate_terms: "Открытый код; отдельные условия весов", client_tested_public_metadata: "Клиент метаданных проверен", documented_adapter_unavailable: "Документация есть; адаптера нет", implemented: "Реализовано", reviewed: "Источник включён в обзор", unreviewed: "Не изучено", reviewed_not_installed: "Изучено; не установлено", reviewed_deployment_recommendation: "Изученный вариант размещения", reviewed_format_recommendation: "Изученный формат упаковки", reviewed_implementation_compatibility_required: "Требуется проверка совместимости", reviewed_legacy_compatibility_only: "Только совместимость со старой версией", reviewed_primary_study_with_correction: "Исследование с поправкой", public_metadata_access: "Открытый API метаданных", access_unverified: "Доступ не проверен", not_verified: "Не проверено", metadata_unverified: "Метаданные не проверены", discovered_unverified: "Найдено; не проверено", builtin_synthetic_control: "Встроенный контрольный расчёт", literature: "Научные публикации", genomics: "Геномика", epigenomics: "Эпигеномика", single_cell: "Одноклеточные данные", tissue_simulation: "Тканевые модели", ml_benchmark: "Проверка ML", quantum_simulation: "Квантовая симуляция", workflow: "Вычислительные конвейеры", local_inventory: "Локальный каталог", publication_metadata: "Метаданные публикации", local_file_metadata: "Локальный файл", reference: "Источник", queued: "В очереди", pending: "Ожидает", leased: "У исполнителя", claimed: "У исполнителя", running: "Выполняется", awaiting_workers: "Ожидает исполнителей", completed: "Завершено", failed: "Ошибка", cancelled: "Отменено", budget_exhausted: "Бюджет исчерпан",
    discovery: "Поиск ресурсов", simulation: "Расчёт", offline: "Локальный каталог", online: "Открытые API", rule_based: "Планирование по правилам", metadata_only: "Только метаданные", unverified: "Не проверено", unknown: "Неизвестно", unavailable: "Недоступно", available: "Доступно", requires_setup: "Требует настройки", planned: "Планируется", adapter_missing: "Адаптер отсутствует", configured: "Профиль настроен", credential_present_unverified: "Переменная задана; вход не проверен", credential_missing: "Нет переменной с секретом", public: "Открытый доступ", open: "Открытый доступ", api_key: "Ключ API", oauth: "OAuth", manual: "Ручное подключение", none: "Без авторизации", requires_user_action: "Требуется ваше действие", no_registration_required: "Регистрация не нужна", requested: "Запрошено", active: "Активен", registered: "Зарегистрирован", stale: "Нет свежего сигнала", disconnected: "Не подключён", trusted_workers: "Доверенные исполнители", local: "Локально", not_installed: "Не установлен", local_builtin: "Встроенный модуль", public_metadata: "Открытые метаданные", unverified_metadata: "Непроверенные метаданные", declared: "Заявлено", not_connected: "Не подключено"
  };
  function node(tag, className, text) { const n = document.createElement(tag); if (className) n.className = className; if (text !== undefined && text !== null) n.textContent = String(text); return n; }
  function arr(value) { return Array.isArray(value) ? value : value == null ? [] : [value]; }
  function label(value) { return labels[value] || String(value == null ? "Не указано" : value); }
  function describe(value) { if (value == null) return "Не указано"; if (typeof value === "string") return value; if (typeof value === "boolean") return value ? "Да" : "Нет"; if (Array.isArray(value)) return value.map(describe).join(" · "); if (typeof value === "object") return value.description || value.message || value.title || value.name || JSON.stringify(value); return String(value); }
  function computation(value) { if (!value) return "Наличие исполняемого адаптера не подтверждено"; if (typeof value === "object") { if (value.reason) return value.reason; if (value.available === true) return `Встроенный адаптер: ${value.plugin_id || "доступен"}`; if (value.available === false || value.adapter_available === false) return "Исполняемый адаптер отсутствует"; } return describe(value); }
  function provenance(value) { if (!value || typeof value !== "object") return describe(value); const parts = []; if (value.provider) parts.push(value.provider); if (value.origin) parts.push(`Реестр: ${value.origin}`); if (value.retrieved_at) parts.push(`Получено: ${fmtDate(value.retrieved_at)}`); if (value.doi) parts.push(`DOI: ${value.doi}`); if (value.filename) parts.push(`Файл: ${value.filename}`); if (value.bytes !== undefined) parts.push(`${value.bytes} байт`); return parts.join(" · ") || "Происхождение не уточнено"; }
  function matchReason(value) { if (typeof value !== "object" || value === null || Array.isArray(value)) return describe(value); const terms = arr(value.terms), groups = arr(value.capabilities).map(label); return [terms.length ? `Совпадения: ${terms.join(", ")}` : "", groups.length ? `Области: ${groups.join(", ")}` : "", value.method || ""].filter(Boolean).join(". ") || describe(value); }
  function fmtDate(value) { if (!value) return "Время не указано"; const d = new Date(typeof value === "number" && value < 1e12 ? value * 1000 : value); return Number.isNaN(d.getTime()) ? String(value) : d.toLocaleString("ru-RU", { dateStyle: "short", timeStyle: "short" }); }
  function badge(value) { let cls = "badge neutral"; if (["completed", "available", "active", "no_registration_required"].includes(value)) cls = "badge"; if (["failed", "unavailable"].includes(value)) cls = "badge error"; if (["pending", "queued", "running", "leased", "awaiting_workers", "requires_user_action", "credential_missing", "budget_exhausted"].includes(value)) cls = "badge warning"; return node("span", cls, label(value)); }
  function empty(title, message) { const box = node("div", "network-empty"); box.append(node("h3", "", title), node("p", "", message)); return box; }
  function list(items) { const ul = node("ul", "network-list"); arr(items).forEach(item => ul.append(node("li", "", describe(item)))); return ul; }
  function link(url, title) { try { const parsed = new URL(url); if (!["http:", "https:"].includes(parsed.protocol) || parsed.username || parsed.password) return null; const a = node("a", "source-link", title); a.href = parsed.href; a.target = "_blank"; a.rel = "noopener noreferrer"; return a; } catch { return null; } }
  function raw(value, title = "Подробные данные", key) { const details = node("details", "network-details"); if (key) details.dataset.key = key; details.append(node("summary", "", title)); const s = JSON.stringify(value, null, 2) || "Нет данных"; details.append(node("pre", "", s.length > 120000 ? `${s.slice(0, 120000)}\n… Для полного результата используйте экспорт.` : s)); return details; }
  function details(title, children, key) { const d = node("details", "network-details"); if (key) d.dataset.key = key; d.append(node("summary", "", title), ...children); return d; }
  function keepOpen(container, render) { const keys = $$('details[open][data-key]', container).map(d => d.dataset.key); render(); $$('details[data-key]', container).forEach(d => { if (keys.includes(d.dataset.key)) d.open = true; }); }
  function message(container, text, error = false) { container.replaceChildren(node("div", error ? "error-panel" : "network-success", text)); }
  function toast(text, error = false) { const n = $("#network-toast"); n.className = error ? "toast error" : "toast"; n.textContent = text; n.hidden = false; clearTimeout(state.toastTimer); state.toastTimer = setTimeout(() => { n.hidden = true; }, 6500); }
  async function api(path, payload) {
    const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 25000);
    try {
      const response = await fetch(path, { method: payload === undefined ? "GET" : "POST", credentials: "same-origin", headers: { Accept: "application/json", ...(payload === undefined ? {} : { "Content-Type": "application/json" }) }, body: payload === undefined ? undefined : JSON.stringify(payload), signal: controller.signal });
      const contentType = response.headers.get("content-type") || "";
      if (!contentType.includes("application/json")) throw new Error(`Сервер вернул неожиданный ответ (${response.status}). Проверьте запуск версии с сетевым контуром.`);
      const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || describe(data.error) || `Ошибка HTTP ${response.status}`); return data;
    } catch (error) { if (error.name === "AbortError") throw new Error("Сервер не ответил за 25 секунд. Обновите состояние: запрос мог быть выполнен."); throw error; } finally { clearTimeout(timer); }
  }
  async function action(button, callback, target) { const original = button.textContent; button.disabled = true; button.textContent = "Выполняется…"; try { await callback(); } catch (error) { if (target) message(target, error.message, true); else toast(error.message, true); } finally { button.disabled = false; button.textContent = original; } }
  function section(name, updateHash = true) { if (!(name in titles)) name = "network"; state.section = name; $$(".network-section").forEach(s => { s.hidden = s.id !== `section-${name}`; }); $$("[data-section]").forEach(b => { b.classList.toggle("active", b.dataset.section === name); if (b.dataset.section === name) b.setAttribute("aria-current", "page"); else b.removeAttribute("aria-current"); }); $("#section-label").textContent = titles[name]; if (updateHash && location.hash !== `#${name}`) history.replaceState(null, "", `#${name}`); }
  function makeTable(headings, rows) { const wrap = node("div", "table-wrap"); const table = node("table"); const thead = node("thead"); const tr = node("tr"); headings.forEach(h => { const th = node("th", "", h); th.scope = "col"; tr.append(th); }); thead.append(tr); const tbody = node("tbody"); rows.forEach(cells => { const row = node("tr"); cells.forEach(content => { const td = node("td"); if (content instanceof Node) td.append(content); else td.textContent = String(content ?? "—"); row.append(td); }); tbody.append(row); }); table.append(thead, tbody); wrap.append(table); return wrap; }
  function button(title, handler, className = "button secondary") { const b = node("button", className, title); b.type = "button"; b.addEventListener("click", () => action(b, handler)); return b; }
  function renderNetwork(data) {
    state.network = data;
    const jobs = arr(data.jobs), workers = arr(data.workers), campaigns = arr(data.campaigns);
    const waiting = jobs.filter(j => !terminal.has(j.status)).length;
    const stats = [["Ресурсы в каталоге", data.resources_count ?? "—"], ["Исполнители в реестре", workers.length], ["Незавершённые задачи", waiting], ["Исследовательские кампании", campaigns.length]];
    $("#network-stats").replaceChildren(...stats.map(([title, count]) => { const card = node("div", "stat-card"); card.append(node("span", "", title), node("strong", "", count)); return card; }));
    const limits = arr(data.limitations); $("#network-limits").hidden = !limits.length; $("#network-limits").replaceChildren(node("span", "note-mark", "i"), list(limits));
    $("#worker-count").textContent = `${workers.length} в реестре`;
    $("#workers").replaceChildren(workers.length ? makeTable(["Исполнитель", "Возможности", "Последний сигнал", "Состояние"], workers.map(w => {
      const id = node("div"); id.append(node("strong", "", w.id || w.worker_id || "Без идентификатора"));
      return [id, arr(w.capabilities).map(label).join(", ") || "Не заявлены", fmtDate(w.last_seen || w.updated_at || w.registered_at || w.created_at), badge(w.status || "registered")];
    })) : empty("Исполнители ещё не подключены", "Запустите worker и укажите адрес координатора. Задачи будут храниться в очереди до появления исполнителя с нужными возможностями."));
    renderJobs(); $("#last-refresh").textContent = `Обновлено ${new Date().toLocaleTimeString("ru-RU")}`;
  }
  function renderJobs() {
    const filter = $("#job-filter").value; let jobs = arr(state.network?.jobs);
    if (filter === "active") jobs = jobs.filter(j => !terminal.has(j.status)); else if (filter !== "all") jobs = jobs.filter(j => j.status === filter);
    if (!jobs.length) { $("#jobs").replaceChildren(empty("Задач пока нет", filter === "all" ? "Поставьте поиск в очередь или запустите исследовательскую кампанию." : "Нет задач с выбранным состоянием.")); return; }
    $("#jobs").replaceChildren(makeTable(["Задача", "Состояние", "Исполнитель", "Попытки", "Действия"], [...jobs].sort((a, b) => String(b.created_at).localeCompare(String(a.created_at))).map(job => {
      const title = node("div"); title.append(node("strong", "", label(job.kind)), node("p", "network-id", job.id));
      const actions = node("div", "button-group"); actions.append(button("Результат", async () => showJob(job)));
      if (!terminal.has(job.status)) actions.append(button("Отменить", async () => { await api("/api/job/cancel", { id: job.id }); await refreshLive(); toast("Отмена задачи сохранена."); }, "button danger"));
      return [title, badge(job.status), job.worker_id || "Не назначен", `${job.attempts ?? 0} / ${job.max_attempts ?? "—"}`, actions];
    })));
  }
  function showJob(job) {
    const panel = node("article", "panel"); const heading = node("div", "result-title"); heading.append(node("h2", "", `${label(job.kind)} · результат`), badge(job.status)); panel.append(heading, node("p", "network-id", job.id));
    const question = job.payload?.query || job.payload?.question || job.payload?.plugin_id; if (question) panel.append(node("p", "result-summary", question));
    if (job.error) panel.append(node("p", "error-panel", describe(job.error)));
    if (!terminal.has(job.status)) panel.append(node("p", "network-small", "Задача ещё не завершена. При следующем открытии здесь появится актуальный результат."));
    if (job.result) { const results = job.result.result || job.result; if (Array.isArray(results.items)) panel.append(node("p", "status-summary", `Найдено записей: ${results.items.length}. Метаданные требуют проверки.`)); if (arr(results.errors).length) panel.append(list(results.errors)); panel.append(raw(job.result, "Результат исполнителя")); }
    panel.append(raw({ id: job.id, kind: job.kind, payload: job.payload, capabilities: job.capabilities, status: job.status, attempts: job.attempts, max_attempts: job.max_attempts, worker_id: job.worker_id, created_at: job.created_at, updated_at: job.updated_at }, "Параметры и происхождение"));
    $("#job-detail").replaceChildren(panel); panel.scrollIntoView({ block: "nearest", behavior: "auto" });
  }
  function renderResources(items) {
    state.resources = arr(items); $("#resource-count").textContent = `${state.resources.length} в текущем списке`;
    const area = $("#resources"); if (!state.resources.length) { area.replaceChildren(empty("Ресурсы не найдены", "Измените запрос или поставьте поиск новых источников в очередь.")); return; }
    keepOpen(area, () => area.replaceChildren(...state.resources.map(resource => {
      const card = node("article", "panel source-card"); const top = node("div", "source-topline"); top.append(node("span", "source-category", label(resource.kind || "Ресурс")), badge(resource.status || "unverified"));
      card.append(top, node("h2", "", resource.title || resource.name || resource.id), node("p", "", resource.description || resource.summary || "Описание не предоставлено."));
      const caps = node("div", "resource-capabilities"); arr(resource.capabilities).slice(0, 12).forEach(c => caps.append(node("span", "", label(c)))); if (caps.childNodes.length) card.append(caps);
      const meta = node("dl", "source-meta"); meta.append(node("dt", "", "Доступ"), node("dd", "", label(resource.access)), node("dt", "", "Вычисления"), node("dd", "", computation(resource.computability || resource.adapter || resource.adapter_status || resource.executable))); card.append(meta);
      const a = link(resource.url, "Открыть первоисточник ↗"); if (a) card.append(a);
      const children = []; if (arr(resource.limitations).length) children.push(list(resource.limitations)); if (resource.provenance) children.push(node("p", "network-small", `Происхождение: ${provenance(resource.provenance)}`)); children.push(node("p", "network-id", resource.id || "Идентификатор не указан")); card.append(details("Происхождение и ограничения", children, `resource-${resource.id}`)); return card;
    })));
  }
  function renderPlan(plan) {
    const panel = node("article", "panel"); const heading = node("div", "result-title"); heading.append(node("h2", "", "План исследования"), badge(plan.mode || "rule_based")); panel.append(heading, node("p", "result-summary", plan.question));
    const columns = node("div", "plan-columns"); const stepsArea = node("div"); stepsArea.append(node("h3", "", "Последовательность работы")); const steps = node("ol", "plan-steps");
    arr(plan.steps).forEach((step, index) => { const li = node("li"); if (typeof step === "object" && step !== null) { li.append(node("strong", "", step.title || step.name || step.action || `Шаг ${index + 1}`)); const detail = step.description || step.purpose || step.task || step.summary; if (detail) li.append(node("p", "", describe(detail))); const extra = Object.fromEntries(Object.entries(step).filter(([key]) => !["title", "name", "action", "description", "purpose", "task", "summary"].includes(key))); if (Object.keys(extra).length) li.append(raw(extra, "Условия шага")); } else li.append(node("p", "", describe(step))); steps.append(li); }); stepsArea.append(steps);
    const resourcesArea = node("div"); resourcesArea.append(node("h3", "", "Подходящие ресурсы")); const ranked = arr(plan.ranked_resources); if (!ranked.length) resourcesArea.append(node("p", "network-small", "В каталоге пока нет подходящих ресурсов."));
    ranked.slice(0, 10).forEach(r => { const resource = r.resource || r; const box = node("div", "plan-resource"); box.append(node("h3", "", resource.title || resource.name || resource.id || r.id || "Ресурс")); const score = r.score ?? r.relevance_score; if (score !== undefined) box.append(node("span", "badge neutral", `Сопоставление по правилам: ${typeof score === "number" ? Number(score.toFixed(3)) : score}`)); const reason = r.match_explanation || r.explanation || r.reasons || r.matches; if (reason) box.append(node("p", "", matchReason(reason))); const capability = r.computability || resource.computability; if (capability) box.append(node("p", "", `Вычислительная доступность: ${computation(capability)}`)); const a = link(resource.url, "Ресурс ↗"); if (a) box.append(a); resourcesArea.append(box); }); columns.append(stepsArea, resourcesArea); panel.append(columns);
    if (arr(plan.gaps).length) panel.append(node("h3", "", "Что ещё требуется"), list(plan.gaps)); if (arr(plan.limits).length) panel.append(details("Границы плана", [list(plan.limits)])); panel.append(raw(plan, "Полный план и оценки ресурсов")); $("#plan-result").replaceChildren(panel);
  }
  function renderCampaigns(items) {
    state.campaigns = arr(items); const area = $("#campaigns");
    if (!state.campaigns.length) { area.replaceChildren(empty("Исследований пока нет", "Сформулируйте вопрос выше. Сначала можно посмотреть план без запуска задач.")); return; }
    keepOpen(area, () => area.replaceChildren(...[...state.campaigns].sort((a, b) => String(b.created_at).localeCompare(String(a.created_at))).map(c => {
      const card = node("article", "panel campaign-card"); const heading = node("div", "network-card-top"); heading.append(node("h3", "", c.question || c.id), badge(c.status)); card.append(heading);
      const meta = node("div", "network-meta"); meta.append(node("span", "campaign-counter", `Итерация ${c.iteration ?? 0} / ${c.max_iterations ?? "—"}`), node("span", "campaign-counter", `Задачи ${arr(c.jobs).length} / ${c.max_jobs ?? "—"}`), badge(c.online ? "online" : "offline")); card.append(meta, node("p", "network-id", `${c.id} · ${fmtDate(c.created_at)}`));
      const progress = node("div", "campaign-progress"); const bar = node("progress"); bar.max = Math.max(1, Number(c.max_iterations) || 1); bar.value = Math.max(0, Math.min(bar.max, Number(c.iteration) || 0)); bar.setAttribute("aria-label", "Выполненные итерации"); progress.append(bar, node("span", "", `${c.iteration ?? 0} из ${c.max_iterations ?? "—"}`)); card.append(progress);
      if (c.error) card.append(node("p", "error-panel", describe(c.error)));
      if (c.status === "awaiting_workers") card.append(node("p", "network-small", "Для продолжения нужен подключённый исполнитель с возможностями задач очереди."));
      const events = arr(c.events); if (events.length) card.append(details(`История: ${events.length} событий`, [list(events.map(e => typeof e === "object" ? `${fmtDate(e.at || e.timestamp || e.created_at)} · ${e.message || e.event || e.type || describe(e)}` : e))], `campaign-events-${c.id}`));
      if (c.plan) card.append(raw(c.plan, "План кампании", `campaign-plan-${c.id}`)); card.append(raw({ jobs: c.jobs, status: c.status, limitations: c.limitations || c.limits, created_at: c.created_at }, "Задачи и параметры", `campaign-data-${c.id}`));
      if (!terminal.has(c.status)) { const actions = node("div", "campaign-actions"); actions.append(button("Продолжить координацию", async () => { const next = await api("/api/campaign/tick", { id: c.id }); await refreshLive(); toast(`Кампания: ${label(next.status)}.`); }), button("Остановить кампанию", async () => { await api("/api/campaign/cancel", { id: c.id }); await refreshLive(); toast("Кампания остановлена."); }, "button danger")); card.append(actions); }
      return card;
    })));
  }
  function renderAccounts(data) {
    state.accounts = arr(data.items); const area = $("#accounts");
    if (!state.accounts.length) area.replaceChildren(empty("Профилей пока нет", "Добавьте профиль провайдера, чтобы зафиксировать способ подключения."));
    else area.replaceChildren(...state.accounts.map(profile => { const card = node("article", "panel source-card"); const top = node("div", "network-card-top"); top.append(node("h2", "", profile.provider || profile.name || "Провайдер"), badge(profile.status || "unknown")); card.append(top, node("p", "network-small", profile.domain));
      const dl = node("dl", "source-meta"); dl.append(node("dt", "", "Авторизация"), node("dd", "", label(profile.auth_mode)), node("dt", "", "Переменная"), node("dd", "", profile.credential_env || "Не задана"), node("dt", "", "Права"), node("dd", "", arr(profile.scopes).join(", ") || "Не указаны")); if (profile.credential_present !== undefined) dl.append(node("dt", "", "Секрет задан"), node("dd", "", profile.credential_present ? "Да; удалённый вход не проверен" : "Нет")); card.append(dl);
      const a = link(profile.setup_url, "Официальная настройка ↗"); if (a) card.append(a);
      card.append(button("Запросить подключение", async () => { $("#registration-provider").value = profile.provider; $("#registration-reason").focus(); $("#registration-form").scrollIntoView({ block: "center", behavior: "auto" }); }, "text-button")); return card; }));
    const selected = $("#registration-provider").value; const initial = node("option", "", state.accounts.length ? "Выберите провайдера" : "Сначала добавьте профиль"); initial.value = ""; $("#registration-provider").replaceChildren(initial, ...state.accounts.map(p => { const o = node("option", "", p.provider); o.value = p.provider; return o; })); if (state.accounts.some(p => p.provider === selected)) $("#registration-provider").value = selected;
    const requests = arr(data.requests); $("#registration-requests").replaceChildren(requests.length ? makeTable(["Провайдер", "Цель", "Состояние", "Создано"], [...requests].reverse().map(r => [r.provider, r.reason || r.message || "—", badge(r.status), fmtDate(r.created_at)])) : empty("Заявок пока нет", "Здесь появится история запросов регистрации и доступа."));
  }
  async function refreshResources() { const serial = ++state.searchSerial; const query = $("#resource-search").value.trim(); const data = await api(`/api/resources?q=${encodeURIComponent(query)}`); if (serial === state.searchSerial) renderResources(data.items); }
  async function refreshAccounts() { renderAccounts(await api("/api/accounts")); }
  async function refreshLive() {
    if (state.refreshing) return; state.refreshing = true;
    try {
      const results = await Promise.allSettled([api("/api/network"), api("/api/campaigns")]);
      if (results[0].status === "fulfilled") { const data = results[0].value; const version = `${data.resources_count}:${arr(data.jobs).filter(j => j.status === "completed").length}`; const changed = state.resourcesVersion !== null && state.resourcesVersion !== version; state.resourcesVersion = version; renderNetwork(data); $("#network-status").textContent = "Координатор доступен"; $("#network-dot").className = "status-dot"; $("#global-error").hidden = true; if (changed) refreshResources().catch(error => toast(error.message, true)); }
      if (results[1].status === "fulfilled") renderCampaigns(results[1].value.items);
      const errors = results.filter(r => r.status === "rejected").map(r => r.reason.message); if (errors.length) { $("#network-status").textContent = "Ошибка обновления"; $("#network-dot").className = "status-dot error"; $("#global-error").textContent = `Не удалось обновить состояние: ${[...new Set(errors)].join(" · ")}`; $("#global-error").hidden = false; }
    } finally { state.refreshing = false; }
  }
  $$("[data-section]").forEach(b => b.addEventListener("click", () => section(b.dataset.section)));
  $$("[data-goto]").forEach(b => b.addEventListener("click", () => section(b.dataset.goto)));
  window.addEventListener("hashchange", () => section(location.hash.slice(1), false));
  $("#job-filter").addEventListener("change", renderJobs);
  $("#refresh-network").addEventListener("click", e => action(e.currentTarget, refreshLive));
  $("#refresh-campaigns").addEventListener("click", e => action(e.currentTarget, refreshLive));
  $("#refresh-accounts").addEventListener("click", e => action(e.currentTarget, refreshAccounts));
  $("#resource-search-form").addEventListener("submit", e => { e.preventDefault(); action($('button[type="submit"]', e.currentTarget), refreshResources, $("#resources")); });
  $("#discovery-form").addEventListener("submit", e => { e.preventDefault(); action($('button[type="submit"]', e.currentTarget), async () => { const job = await api("/api/discover", { query: $("#discovery-query").value.trim(), limit: Number($("#discovery-limit").value), offline: !$("#discovery-online").checked }); message($("#discovery-result"), `Поиск поставлен в очередь: ${job.id}. Состояние: ${label(job.status)}. Результаты появятся после выполнения исполнителем.`); await refreshLive(); }, $("#discovery-result")); });
  $("#local-form").addEventListener("submit", e => { e.preventDefault(); action($('button[type="submit"]', e.currentTarget), async () => { const result = await api("/api/local-resources", { path: $("#local-path").value.trim() }); $("#local-result").replaceChildren(node("div", "network-success", "Проверка каталога завершена."), raw(result, "Результаты локальной проверки")); await refreshResources(); await refreshLive(); }, $("#local-result")); });
  $("#make-plan").addEventListener("click", e => { if (!$("#research-question").reportValidity()) return; action(e.currentTarget, async () => renderPlan(await api("/api/plan", { question: $("#research-question").value.trim() })), $("#plan-result")); });
  $("#campaign-form").addEventListener("submit", e => { e.preventDefault(); action($('button[type="submit"]', e.currentTarget), async () => { const campaign = await api("/api/campaign", { question: $("#research-question").value.trim(), max_iterations: Number($("#campaign-iterations").value), max_jobs: Number($("#campaign-jobs").value), online: $("#campaign-online").checked, simulate: $("#campaign-simulate").checked }); message($("#campaign-result"), `Кампания ${campaign.id} создана. Состояние: ${label(campaign.status)}.`); if (campaign.plan) renderPlan(campaign.plan); await refreshLive(); }, $("#campaign-result")); });
  $("#account-auth").addEventListener("change", () => { const mode = $("#account-auth").value; $("#account-env").disabled = mode === "none" || mode === "manual"; $("#account-env").required = mode === "api_key"; if ($("#account-env").disabled) $("#account-env").value = ""; });
  $("#account-form").addEventListener("submit", e => { e.preventDefault(); action($('button[type="submit"]', e.currentTarget), async () => { const payload = { provider: $("#account-provider").value.trim(), domain: $("#account-domain").value.trim(), auth_mode: $("#account-auth").value, scopes: $("#account-scopes").value.split(",").map(s => s.trim()).filter(Boolean) }; if (!$("#account-env").disabled && $("#account-env").value.trim()) payload.credential_env = $("#account-env").value.trim(); if ($("#account-setup").value.trim()) payload.setup_url = $("#account-setup").value.trim(); const profile = await api("/api/accounts", payload); message($("#account-result"), `Профиль «${profile.provider}» сохранён. Состояние: ${label(profile.status)}.`); await refreshAccounts(); }, $("#account-result")); });
  $("#registration-form").addEventListener("submit", e => { e.preventDefault(); action($('button[type="submit"]', e.currentTarget), async () => { const record = await api("/api/accounts/request", { provider: $("#registration-provider").value, reason: $("#registration-reason").value.trim() }); message($("#registration-result"), `Заявка сохранена: ${label(record.status)}.${record.message ? ` ${record.message}` : ""}`); const a = link(record.setup_url, "Продолжить на официальном сайте ↗"); if (a) $("#registration-result").append(a); await refreshAccounts(); }, $("#registration-result")); });
  section(location.hash.slice(1), false);
  async function boot() { const results = await Promise.allSettled([refreshLive(), refreshResources(), refreshAccounts()]); results.forEach((result, index) => { if (result.status === "rejected") { const target = index === 1 ? $("#resources") : index === 2 ? $("#accounts") : $("#global-error"); message(target, result.reason.message, true); target.hidden = false; } }); }
  boot();
  const poll = setInterval(() => { if (!document.hidden) refreshLive().catch(error => toast(error.message, true)); }, 8000);
  document.addEventListener("visibilitychange", () => { if (!document.hidden) refreshLive().catch(error => toast(error.message, true)); });
  window.addEventListener("pagehide", () => clearInterval(poll), { once: true });
})();
