"use strict";
(() => {
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => Array.from(root.querySelectorAll(selector));
  const state = { data: null, refreshing: false, toastTimer: null, section: "missions", renderedMissions: null, renderedAgents: null, renderedSnapshots: null, renderedRoles: null, renderedClaims: null, renderedDirectory: null };
  const sections = { missions: "Миссии", registry: "Агенты и платформы", directory: "Живые каталоги", claims: "Журнал утверждений", snapshots: "Копии исходного кода" };
  const terminal = new Set(["completed", "partial", "failed", "cancelled"]);
  const labels = {
    directory: "Поиск в каталоге", agentverse: "Agentverse", huggingface_models: "Hugging Face · модели", huggingface_datasets: "Hugging Face · наборы данных", directory_listed_not_connected: "Найдено в каталоге · не подключено", public_github_pinned_archive: "Публичный GitHub, закреплённый коммит", user_supplied_archive_unverified_origin: "Локальный архив; происхождение не подтверждено", dataset: "Набор данных",
    agent: "Агент", framework: "Фреймворк", platform: "Платформа", model: "Модель", tool: "Инструмент", protocol: "Протокол",
    clear_web: "Публичная сеть", authenticated: "С авторизацией", private: "Закрытая сеть", onion: "Onion / Tor", public: "Публичные сведения", internal: "Внутренние данные", sensitive_genomic: "Чувствительные геномные данные",
    published_study: "Опубликованное исследование", authors_benchmark: "Тесты авторов", product_claim: "Заявление поставщика", documentation: "Документация",
    documented_not_connected: "Изучено · не подключено", public_documentation_only: "По публичной документации", source_inspected_not_executed: "Исходники проверены · не запускались",
    allowed: "Публичный маршрут доступен", local_only: "Только локальная обработка", requires_connection: "Требуется подключение", unsupported_transport: "Транспорт не реализован",
    created: "Создано", queued: "В очереди", running: "Выполняется", awaiting_workers: "Ожидает исполнителей", completed: "Вычислительный цикл завершён", partial: "Частичный результат", failed: "Ошибка", invalid_result: "Результат не прошёл проверку", cancelled: "Отменено",
    discovery: "Поиск ресурсов", evidence: "Разбор источников", simulation: "Методический контроль", online: "Публичные API", offline: "Локальный каталог", offline_index: "Локальный индекс", public_abstract_triage: "Предварительный разбор аннотаций",
    unreviewed: "Не оценено", supported_within_scope: "Поддерживается в указанной области", contradicted: "Противоречит источникам", inconclusive: "Данных недостаточно",
    scout: "Разведчик", curator: "Куратор", methodologist: "Методолог", implementer: "Инженер", reproducer: "Воспроизводитель", critic: "Критик", coordinator: "Координатор",
    mission_created: "Миссия создана", bounded_jobs_submitted: "Задачи поставлены в очередь", results_checked: "Структура результатов проверена", mission_stopped: "Цикл остановлен", mission_cancelled: "Миссия отменена",
    human: "Упоминание человека", animal: "Упоминание животных", in_vitro: "Упоминание in vitro", deterministic_workflow: "Процесс по правилам"
  };
  function node(tag, className, text) { const n = document.createElement(tag); if (className) n.className = className; if (text !== undefined && text !== null) n.textContent = String(text); return n; }
  function arr(value) { return Array.isArray(value) ? value : value == null ? [] : [value]; }
  function describe(value) { if (value == null) return "Не указано"; if (typeof value === "string") return value; if (typeof value === "boolean") return value ? "Да" : "Нет"; if (Array.isArray(value)) return value.map(describe).join(" · "); if (typeof value === "object") return value.description || value.message || value.title || value.name || JSON.stringify(value); return String(value); }
  function label(value) { return labels[value] || describe(value); }
  function fmtDate(value) { if (!value) return "Не указано"; const d = new Date(typeof value === "number" && value < 1e12 ? value * 1000 : value); return Number.isNaN(d.getTime()) ? String(value) : d.toLocaleString("ru-RU", { dateStyle: "short", timeStyle: "short" }); }
  function badge(value) { const cls = ["failed", "invalid_result", "contradicted"].includes(value) ? "badge error" : ["partial", "running", "queued", "awaiting_workers", "requires_connection", "unsupported_transport"].includes(value) ? "badge warning" : ["completed", "allowed"].includes(value) ? "badge" : "badge neutral"; return node("span", cls, label(value)); }
  function list(items, className = "network-list") { const ul = node("ul", className); arr(items).forEach(item => ul.append(node("li", "", describe(item)))); return ul; }
  function empty(title, text) { const n = node("div", "network-empty"); n.append(node("h3", "", title), node("p", "", text)); return n; }
  function externalLink(url, title) { try { if (typeof url !== "string" || /[\u0000-\u0020\u007f\\]/.test(url)) return null; const parsed = new URL(url); if (!["http:", "https:"].includes(parsed.protocol) || parsed.username || parsed.password) return null; const a = node("a", "source-link", title); a.href = parsed.href; a.rel = "noopener noreferrer"; a.target = "_blank"; return a; } catch { return null; } }
  function details(title, content, key, className = "network-details") { const n = node("details", className); if (key) n.dataset.key = key; n.append(node("summary", "", title), ...arr(content)); return n; }
  function raw(value, title, key) { const text = JSON.stringify(value, null, 2) || "Нет данных"; return details(title || "Исходные данные", node("pre", "", text.length > 120000 ? `${text.slice(0,120000)}\n… Полные данные доступны в экспорте.` : text), key); }
  function replacePreservingOpen(container, children) { const open = new Set($$("details[open][data-key]", container).map(n => n.dataset.key)); container.replaceChildren(...arr(children)); $$("details[data-key]", container).forEach(n => { n.open = open.has(n.dataset.key); }); }
  function feedback(target, text, error = false) { target.replaceChildren(node("div", error ? "error-panel" : "network-success", text)); }
  function toast(text, error = false) { const n = $("#society-toast"); n.textContent = text; n.className = error ? "toast error" : "toast"; n.hidden = false; clearTimeout(state.toastTimer); state.toastTimer = setTimeout(() => { n.hidden = true; }, 7000); }
  async function api(path, body, timeout = 35000) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout); try { const response = await fetch(path, { method: body === undefined ? "GET" : "POST", credentials: "same-origin", headers: { Accept: "application/json", ...(body === undefined ? {} : { "Content-Type": "application/json" }) }, body: body === undefined ? undefined : JSON.stringify(body), signal: controller.signal }); if (!(response.headers.get("content-type") || "").includes("application/json")) throw new Error(`Неожиданный ответ сервера (${response.status}). Проверьте, что запущен Meta-Harness v0.6.`); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || describe(data.error) || `Ошибка HTTP ${response.status}`); return data; } catch (error) { if (error.name === "AbortError") throw new Error("Время ожидания истекло. Сначала обновите состояние: запрос мог завершиться на сервере."); throw error; } finally { clearTimeout(timer); } }
  async function action(button, callback, target) { if (button.disabled) return; const original = button.textContent; button.disabled = true; button.textContent = "Выполняется…"; button.setAttribute("aria-busy", "true"); try { await callback(); } catch (error) { if (target) feedback(target, error.message, true); else toast(error.message, true); } finally { button.disabled = false; button.textContent = original; button.removeAttribute("aria-busy"); enforcePolicy(); } }
  function actionButton(title, callback, className = "button secondary") { const button = node("button", className, title); button.type = "button"; button.addEventListener("click", () => action(button, callback)); return button; }
  function section(name, updateHash = true) { if (!(name in sections)) name = "missions"; state.section = name; $$(".society-section").forEach(n => { n.hidden = n.id !== `section-${name}`; }); $$("[data-section]").forEach(n => { n.classList.toggle("active", n.dataset.section === name); if (n.dataset.section === name) n.setAttribute("aria-current", "page"); else n.removeAttribute("aria-current"); }); $("#section-label").textContent = sections[name]; if (updateHash && location.hash !== `#${name}`) history.replaceState(null, "", `#${name}`); }
  function missionSources(mission) { const unique = new Map(); [...arr(mission?.evidence_items), ...arr(mission?.discovery_items)].forEach(item => { if (item.id && !unique.has(item.id)) unique.set(item.id, item); }); return [...unique.values()]; }
  function renderAgents() {
    const query = $("#agent-search").value.trim().toLocaleLowerCase(); const kind = $("#agent-kind").value; const layer = $("#agent-layer").value;
    const agents = arr(state.data?.agents).filter(a => (!query || JSON.stringify(a).toLocaleLowerCase().includes(query)) && (!kind || a.entity_type === kind) && (!layer || arr(a.network_layers).includes(layer)));
    $("#registry-count").textContent = `${agents.length} из ${arr(state.data?.agents).length}`;
    if (!agents.length) { $("#agents").replaceChildren(empty("Совпадений нет", "Измените поисковый запрос или фильтры. Каталог содержит только исследованные решения.")); return; }
    replacePreservingOpen($("#agents"), agents.map(agent => {
      const card = node("article", "panel source-card agent-card"); card.append(node("p", "agent-type", label(agent.entity_type)));
      const top = node("div", "network-card-top"); top.append(node("h2", "", agent.name), badge(agent.integration_status || "documented_not_connected")); card.append(top, node("p", "agent-organization", agent.organization));
      const caps = node("div", "resource-capabilities"); arr(agent.capabilities).forEach(c => caps.append(node("span", "", describe(c)))); card.append(caps);
      const meta = node("dl", "agent-meta"); [["Сеть", arr(agent.network_layers).map(label).join(" · ")], ["Основание", label(agent.evidence_level)], ["Доступ", describe(agent.access_mode)], ["Лицензия", describe(agent.license)], ["Проверено", fmtDate(agent.checked_at)]].forEach(([key,value]) => meta.append(node("dt", "", key), node("dd", "", value))); card.append(meta, node("p", "evidence-summary", describe(agent.evidence_summary)));
      const links = node("div", "agent-links"); const source = externalLink(agent.source_url, "Первоисточник ↗"); const docs = externalLink(agent.docs_url, "Документация ↗"); if (source) links.append(source); if (docs && agent.docs_url !== agent.source_url) links.append(docs); card.append(links);
      const body = [node("h3", "", "Достоинства"), list(agent.strengths), node("h3", "", "Ограничения и риски"), list(agent.weaknesses), node("h3", "", "Как воспроизвести или подключить"), node("p", "", describe(agent.copy_strategy)), node("h3", "", "Качество источников"), node("p", "", describe(agent.source_quality))];
      const provenance = node("div", "agent-links"); arr(agent.provenance_urls).forEach((url,i) => { const link = externalLink(url, `Источник ${i+1} ↗`); if (link) provenance.append(link); }); if (provenance.childNodes.length) body.push(provenance);
      card.append(details("Возможности, риски и интеграция", body, `agent-${agent.id}`, "agent-details")); return card;
    }));
  }
  function renderRoute(route) {
    const panel = node("article", "panel route-panel"); const heading = node("div", "route-heading"); heading.append(node("h2", "", "Предлагаемый маршрут"), badge(route.decision)); panel.append(heading, list(route.reasons));
    const columns = node("div", "route-columns"); const steps = node("div"); steps.append(node("h3", "", "Порядок работы"), list(route.steps, "plan-steps")); const candidates = node("div"); candidates.append(node("h3", "", "Ресурсы, соответствующие запросу"));
    const ranked = arr(route.ranked_agents); const grid = node("div", "route-agents"); ranked.forEach(entry => { const agent = entry.agent || entry; const row = node("div", "route-agent"); row.append(node("strong", "", agent.name || agent.id || "Ресурс"), node("p", "", agent.organization || "")); if (entry.matched_terms) row.append(node("p", "", `Совпадения: ${arr(entry.matched_terms).join(", ")}`)); row.append(node("p", "", label(agent.integration_status || "documented_not_connected"))); grid.append(row); }); candidates.append(ranked.length ? grid : node("p", "form-help", "В локальном каталоге нет совпадений. Уточните термины вопроса; это не означает отсутствия подходящих научных решений.")); columns.append(steps, candidates); panel.append(columns, node("p", "form-help", "Ранжирование основано на совпадении терминов. Позиция в списке не является оценкой научной достоверности.")); if (arr(route.limits).length) panel.append(details("Ограничения маршрута", list(route.limits))); $("#route-result").replaceChildren(panel);
  }
  function evidenceCard(item) { const card = node("article", "evidence-card"); card.append(node("h4", "", item.title || item.name || item.id), node("p", "network-id", item.id)); const source = externalLink(item.url, "Открыть источник ↗"); if (source) card.append(source); if (item.doi) card.append(node("p", "", `DOI: ${item.doi}`)); card.append(node("p", "", item.abstract_available ? "Аннотация получена; сохранена контрольная сумма." : "Аннотация не получена; доступны сведения об источнике.")); if (item.excerpt) card.append(node("p", "", `Краткий фрагмент: «${item.excerpt}»`)); const indicators = node("div"); arr(item.indicators).forEach(i => indicators.append(node("span", "indicator", label(i)))); if (indicators.childNodes.length) card.append(indicators, node("p", "", "Признаки определены по словам и требуют проверки статьи.")); const origin = item.provenance || {}; card.append(node("p", "", `Источник данных по отчёту исполнителя: ${origin.provider || "Не указан"} · ${fmtDate(origin.retrieved_at)}`)); if (arr(item.limitations).length) card.append(list(item.limitations)); if (item.abstract_sha256) card.append(raw({ abstract_sha256: item.abstract_sha256, provenance: origin }, "Происхождение и хеш", `evidence-hash-${item.id}`)); return card; }
  function renderMissions(missions) {
    $("#mission-count").textContent = `${missions.length} миссий`;
    if (!missions.length) { $("#missions").replaceChildren(empty("Первое исследование начинается с вопроса", "Выберите режим, оцените маршрут и запустите миссию. Её задачи и результаты появятся здесь.")); return; }
    replacePreservingOpen($("#missions"), missions.map(mission => {
      const card = node("article", "panel mission-card"); const top = node("div", "network-card-top"); top.append(node("h3", "", mission.question), badge(mission.status)); card.append(top, node("p", "network-id", mission.id));
      const meta = node("div", "network-meta"); meta.append(badge(mission.online ? "online" : "offline"), badge(mission.data_class), node("span", "network-small", fmtDate(mission.created_at))); card.append(meta);
      const jobs = arr(mission.job_details).length ? arr(mission.job_details) : arr(mission.jobs); const strip = node("div", "mission-job-strip"); jobs.forEach(job => { const n = node("div", "mission-job", typeof job === "string" ? job : label(job.kind)); if (typeof job === "object") n.append(node("small", "", `${label(job.status)}${job.worker_id ? ` · ${job.worker_id}` : ""}`)); strip.append(n); }); if (jobs.length) card.append(strip);
      if (mission.status === "awaiting_workers") card.append(node("p", "form-help", "Для выполнения нужны процессы исполнителей. Запуск start.sh / start.cmd поднимает локальную сеть с исполнителями."));
      const evidence = arr(mission.evidence_items); if (evidence.length) { const grid = node("div", "mission-evidence-grid"); evidence.forEach(item => grid.append(evidenceCard(item))); card.append(details(`Источники и аннотации · ${evidence.length}`, grid, `mission-evidence-${mission.id}`)); }
      const found = arr(mission.discovery_items); if (found.length) { const foundItems = node("ul", "network-list"); found.forEach(item => { const li = node("li"); const a = externalLink(item.url, item.title || item.name || item.id); li.append(a || node("span", "", item.title || item.name || item.id), node("div", "network-id", item.id)); foundItems.append(li); }); card.append(details(`Результаты поиска · ${found.length}`, foundItems, `mission-discovery-${mission.id}`)); }
      const methods = arr(mission.method_results); if (methods.length) { const results = node("div"); results.append(node("p", "form-help", "Методический контроль проверяет вычислительный процесс на искусственных данных. Он не оценивает изменение взрослого организма.")); methods.forEach((result,i) => results.append(raw(result, result.plugin_id || `Контрольный расчёт ${i+1}`, `mission-method-${mission.id}-${i}`))); card.append(details(`Методологические результаты · ${methods.length}`, results, `mission-methods-${mission.id}`)); }
      if (mission.status === "completed" && !evidence.length) card.append(node("p", "form-help", "Цикл выполнен; подходящих источников с аннотациями не получено. Уточните запрос и проверьте результаты поиска."));
      if (arr(mission.issues).length) card.append(details("Неполные результаты и ошибки", node("pre", "", JSON.stringify(mission.issues, null, 2)), `mission-issues-${mission.id}`));
      const events = arr(mission.events); if (events.length) card.append(details(`История координации · ${events.length}`, list(events.map(e => `${fmtDate(e.at || e.created_at)} · ${label(e.role)} · ${label(e.event || e.message)}`), "mission-event-list"), `mission-events-${mission.id}`));
      card.append(raw({ budget: mission.budget, jobs: mission.job_details || mission.jobs, limitations: mission.limitations, route: mission.route }, "Параметры, происхождение и ограничения", `mission-data-${mission.id}`));
      const actions = node("div", "campaign-actions"); if (!terminal.has(mission.status)) actions.append(actionButton("Продолжить", async () => { await api("/api/society/mission/tick", { id: mission.id }); await refresh(); }), actionButton("Отменить миссию", async () => { await api("/api/society/mission/cancel", { id: mission.id }); await refresh(); toast("Отмена миссии сохранена."); }, "button danger")); actions.append(actionButton("Добавить утверждение", async () => { $("#claim-mission").value = mission.id; renderClaimSources(); section("claims"); $("#claim-text").focus(); }, "text-button")); card.append(actions); return card;
    }));
  }
  function renderClaimSources() { const selected = new Set($$("input:checked", $("#claim-sources")).map(input => input.value)); const mission = arr(state.data?.missions).find(m => m.id === $("#claim-mission").value); const sources = missionSources(mission); const area = $("#claim-sources"); if (!sources.length) { area.replaceChildren(node("p", "muted", mission ? "У миссии пока нет полученных источников. Можно сохранить неоценённое утверждение." : "Сначала выберите миссию.")); return; } area.replaceChildren(...sources.map(source => { const labelNode = node("label", "checkbox-label source-choice"); const input = node("input"); input.type = "checkbox"; input.value = source.id; input.checked = selected.has(source.id); const name = node("span", "", source.title || source.name || source.id); name.append(node("small", "", source.id)); labelNode.append(input, name); return labelNode; })); }
  function renderClaims(missions) {
    const claims = missions.flatMap(m => arr(m.claims).map(c => ({ ...c, mission_question: m.question }))); $("#claims-count").textContent = `${claims.length} утверждений`;
    const selected = $("#claim-mission").value; const option = node("option", "", missions.length ? "Выберите миссию" : "Сначала создайте миссию"); option.value = ""; $("#claim-mission").replaceChildren(option, ...missions.map(m => { const opt = node("option", "", m.question.length > 120 ? `${m.question.slice(0,117)}…` : m.question); opt.value = m.id; return opt; })); if (missions.some(m => m.id === selected)) $("#claim-mission").value = selected; renderClaimSources();
    if (!claims.length) { $("#claims").replaceChildren(empty("Утверждений пока нет", "После исследования зафиксируйте, что именно показывают источники и к какой области относится вывод.")); return; }
    replacePreservingOpen($("#claims"), [...claims].reverse().map(claim => { const card = node("article", "panel claim-card"); const top = node("div", "network-card-top"); top.append(node("h3", "", claim.text), badge(claim.assessment)); card.append(top, node("p", "user-assessment", `Оценка пользователя · ${fmtDate(claim.created_at)} · Независимая проверка не подтверждена`), node("p", "claim-label", "Область применимости"), node("p", "", claim.scope)); if (claim.rationale) card.append(node("p", "claim-label", "Обоснование"), node("p", "", claim.rationale)); card.append(node("p", "claim-label", "Миссия"), node("p", "", claim.mission_question), raw({ id: claim.id, mission_id: claim.mission_id, source_ids: claim.source_ids, assessed_by: claim.assessed_by, independently_validated: claim.independently_validated }, "Источники и происхождение оценки", `claim-${claim.id}`)); return card; }));
  }
  function renderSnapshots(snapshots) { $("#snapshot-count").textContent = `${snapshots.length} снимков`; if (!snapshots.length) { $("#snapshots").replaceChildren(empty("Исходники ещё не скопированы", "Укажите публичный репозиторий, точный коммит и лицензию. После проверки здесь появится запись снимка.")); return; } replacePreservingOpen($("#snapshots"), snapshots.map(record => { const card = node("article", "panel snapshot-record"); const top = node("div", "network-card-top"); top.append(node("h3", "", record.repository || record.id || "Снимок"), badge(record.status || "source_inspected_not_executed")); card.append(top); const meta = node("dl", "source-meta"); [["Коммит", record.commit], ["Лицензия", record.license_spdx || record.license], ["SHA-256 архива", record.archive_sha256 || record.sha256], ["Файлов", record.file_count ?? record.files_count], ["Происхождение", record.provenance?.mode ? label(record.provenance.mode) : describe(record.provenance || record.origin)], ["Сохранено", fmtDate(record.created_at || record.inspected_at)]].forEach(([key,value]) => meta.append(node("dt", "", key), node("dd", "", value ?? "Не указано"))); card.append(meta, raw(record, "Полная запись инспекции", `snapshot-${record.id || record.commit}`)); return card; })); }
  function renderDirectory(jobs) {
    $("#directory-count").textContent = `${jobs.length} запросов`;
    if (!jobs.length) { $("#directory-jobs").replaceChildren(empty("Запросов к каталогам пока нет", "Выберите каталог, задайте тему и режим поиска. Задачу выполнит подключённый исполнитель.")); return; }
    replacePreservingOpen($("#directory-jobs"), [...jobs].sort((a,b) => String(b.created_at).localeCompare(String(a.created_at))).map(job => {
      const card = node("article", "panel mission-card"); const payload = job.payload || {}; const result = job.result || {}; const top = node("div", "network-card-top"); top.append(node("h3", "", payload.query || result.query || "Поиск в каталоге"), badge(job.status)); card.append(top, node("p", "network-id", job.id)); const meta = node("div", "network-meta"); meta.append(badge(payload.provider || result.provider), badge(payload.offline === false ? "online" : "offline"), node("span", "network-small", fmtDate(job.created_at))); card.append(meta);
      if (job.error) card.append(node("p", "error-panel", describe(job.error)));
      if (arr(result.errors).length) card.append(details("Ошибки провайдера", list(result.errors), `directory-errors-${job.id}`));
      const items = arr(result.items); const grid = node("div", "mission-evidence-grid"); items.forEach(item => { const entry = node("article", "evidence-card"); entry.append(node("h4", "", item.name || item.title || item.id), node("p", "", item.organization || "Организация не указана"), badge(item.status || "directory_listed_not_connected"), node("p", "", `Тип: ${label(item.entity_type)} · Лицензия: ${describe(item.license)}`)); const link = externalLink(item.url, "Запись в каталоге ↗"); if (link) entry.append(link); if (arr(item.capabilities).length) entry.append(node("p", "", `Заявленные возможности: ${arr(item.capabilities).map(describe).join(" · ")}`)); if (item.revision) entry.append(node("p", "network-id", `Версия: ${describe(item.revision)}`)); if (arr(item.limitations).length) entry.append(list(item.limitations)); entry.append(raw({ id: item.id, provenance: item.provenance }, "Идентификатор и происхождение", `directory-entry-${job.id}-${item.id}`)); grid.append(entry); });
      if (items.length) card.append(grid); else if (job.status === "completed") card.append(node("p", "form-help", payload.offline ? "Локальный режим завершён. Актуальный каталог не запрашивался." : "Ответ получен; подходящих записей нет или провайдер вернул ограничения. Проверьте детали запроса.")); else if (["queued", "running"].includes(job.status)) card.append(node("p", "form-help", "Задача ожидает исполнителя или выполняется. Статус обновляется автоматически."));
      card.append(raw({ payload: job.payload, result: job.result, worker_id: job.worker_id, attempts: job.attempts, result_validation: job.result_validation, error: job.error }, "Параметры и отчёт исполнителя", `directory-job-${job.id}`)); return card;
    }));
  }
  function render(data) {
    state.data = data; const missions = arr(data.missions); const claims = missions.reduce((sum,m) => sum + arr(m.claims).length, 0);
    const stats = [["Документированные решения", arr(data.agents).length], ["Исследовательские миссии", missions.length], ["Утверждения пользователя", claims], ["Снимки исходников", arr(data.snapshots).length]]; $("#society-stats").replaceChildren(...stats.map(([title,count]) => { const n = node("div", "stat-card"); n.append(node("span", "", title), node("strong", "", count)); return n; }));
    const agentsKey = JSON.stringify(data.agents); if (agentsKey !== state.renderedAgents) { renderAgents(); state.renderedAgents = agentsKey; }
    const missionsKey = JSON.stringify(data.missions); if (missionsKey !== state.renderedMissions) { renderMissions(missions); renderClaims(missions); state.renderedMissions = missionsKey; }
    const directoryKey = JSON.stringify(data.directory_jobs); if (directoryKey !== state.renderedDirectory) { renderDirectory(arr(data.directory_jobs)); state.renderedDirectory = directoryKey; }
    const snapshotsKey = JSON.stringify(data.snapshots); if (snapshotsKey !== state.renderedSnapshots) { renderSnapshots(arr(data.snapshots)); state.renderedSnapshots = snapshotsKey; }
    const rolesKey = JSON.stringify(data.roles); if (rolesKey !== state.renderedRoles) { $("#roles").replaceChildren(...arr(data.roles).map(role => { const card = node("div", "role-card"); card.append(node("h3", "", role.name || label(role.id || role)), node("p", "", role.function || role.description || "Функция координации по правилам")); return card; })); state.renderedRoles = rolesKey; }
    $("#society-limits").hidden = !arr(data.limits).length; $("#society-limits").replaceChildren(node("span", "note-mark", "i"), list(data.limits)); $("#last-refresh").textContent = `Обновлено ${new Date().toLocaleTimeString("ru-RU")}`;
  }
  async function refresh() { if (state.refreshing) return; state.refreshing = true; try { render(await api("/api/society")); $("#society-dot").className = "status-dot"; $("#society-status").textContent = "Координатор доступен"; $("#global-error").hidden = true; } catch (error) { $("#society-dot").className = "status-dot error"; $("#society-status").textContent = "Ошибка обновления"; $("#global-error").hidden = false; $("#global-error").textContent = `Не удалось обновить состояние. ${error.message}`; } finally { state.refreshing = false; } }
  function enforcePolicy() { const directoryPublic = $("#directory-data").value === "public"; $("#directory-online").disabled = !directoryPublic; if (!directoryPublic) $("#directory-online").checked = false; $("#directory-policy").textContent = directoryPublic ? "По умолчанию используется локальный режим. В онлайн-режиме текст запроса передаётся выбранному каталогу." : "Непубличный запрос обрабатывается локально; передача внешнему каталогу отключена."; const isPublic = $("#mission-data").value === "public"; const availableTransport = $("#mission-layer").value === "clear_web"; $("#mission-online").disabled = !isPublic || !availableTransport; if (!isPublic || !availableTransport) $("#mission-online").checked = false; if (!$("#mission-start").hasAttribute("aria-busy")) $("#mission-start").disabled = !availableTransport; $("#mission-policy").textContent = !availableTransport ? "Для этого слоя доступна оценка маршрута. Исполняемого коннектора нет; для запуска миссии выберите публичную сеть или локальную обработку в ней." : !isPublic ? "Запрос останется в локальном контуре. Передача внутренних и чувствительных данных внешним сервисам отключена." : "Без внешних обращений используется локальный каталог. Онлайн-запрос передаётся открытым научным API."; }
  $$("[data-section]").forEach(button => button.addEventListener("click", () => section(button.dataset.section)));
  ["agent-search", "agent-kind", "agent-layer"].forEach(id => $("#" + id).addEventListener(id === "agent-search" ? "input" : "change", renderAgents));
  $("#refresh-society").addEventListener("click", event => action(event.currentTarget, refresh));
  $("#mission-data").addEventListener("change", enforcePolicy); $("#mission-layer").addEventListener("change", enforcePolicy);
  $("#route-button").addEventListener("click", event => { if (!$("#mission-question").reportValidity()) return; action(event.currentTarget, async () => { const result = await api("/api/society/route", { question: $("#mission-question").value.trim(), data_class: $("#mission-data").value, network_layer: $("#mission-layer").value }); renderRoute(result); }, $("#mission-feedback")); });
  $("#mission-form").addEventListener("submit", event => { event.preventDefault(); if ($("#mission-layer").value !== "clear_web") return; action($("#mission-start"), async () => { const result = await api("/api/society/mission", { question: $("#mission-question").value.trim(), data_class: $("#mission-data").value, online: $("#mission-online").checked, max_sources: Number($("#mission-limit").value) }); feedback($("#mission-feedback"), `Миссия создана: ${result.id}. ${label(result.status)}.`); await refresh(); }, $("#mission-feedback")); });
  $("#directory-data").addEventListener("change", enforcePolicy);
  $("#directory-form").addEventListener("submit", event => { event.preventDefault(); const button = $('button[type="submit"]', event.currentTarget); action(button, async () => { const job = await api("/api/society/directory", { query: $("#directory-query").value.trim(), provider: $("#directory-provider").value, limit: Number($("#directory-limit").value), offline: !$("#directory-online").checked, data_class: $("#directory-data").value }); feedback($("#directory-feedback"), `Поиск поставлен в очередь: ${job.id}. Полученные записи появятся ниже.`); await refresh(); }, $("#directory-feedback")); });
  $("#claim-mission").addEventListener("change", () => { $("#claim-sources").replaceChildren(); renderClaimSources(); });
  $("#claim-assessment").addEventListener("change", () => { $("#claim-rationale").required = $("#claim-assessment").value !== "unreviewed"; });
  $("#claim-form").addEventListener("submit", event => { event.preventDefault(); const button = $('button[type="submit"]', event.currentTarget); action(button, async () => { const sourceIds = $$("input:checked", $("#claim-sources")).map(n => n.value); if ($("#claim-assessment").value !== "unreviewed" && !sourceIds.length) throw new Error("Выберите хотя бы один источник для оценки утверждения."); const result = await api("/api/society/claim", { mission_id: $("#claim-mission").value, text: $("#claim-text").value.trim(), scope: $("#claim-scope").value.trim(), source_ids: sourceIds, assessment: $("#claim-assessment").value, rationale: $("#claim-rationale").value.trim() }); feedback($("#claim-feedback"), `Утверждение сохранено как оценка пользователя: ${result.id}.`); $("#claim-text").value = ""; $("#claim-rationale").value = ""; $("#claim-assessment").value = "unreviewed"; $("#claim-rationale").required = false; await refresh(); }, $("#claim-feedback")); });
  $("#snapshot-form").addEventListener("submit", event => { event.preventDefault(); const button = $('button[type="submit"]', event.currentTarget); action(button, async () => { const record = await api("/api/society/snapshot", { repository: $("#snapshot-repository").value.trim(), commit: $("#snapshot-commit").value.trim().toLowerCase(), license_spdx: $("#snapshot-license").value }, 60000); feedback($("#snapshot-feedback"), `Снимок сохранён: ${record.repository || record.id}. Исходники не выполнялись.`); await refresh(); }, $("#snapshot-feedback")); });
  window.addEventListener("hashchange", () => section(location.hash.slice(1), false));
  document.addEventListener("visibilitychange", () => { if (!document.hidden) refresh(); });
  section(location.hash.slice(1) || "missions", false); enforcePolicy(); refresh(); setInterval(() => { if (!document.hidden) refresh(); }, 5000);
})();
